package Pojos;
// Generated 26 ene. 2021 7:44:13 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Artista generated by hbm2java
 */
@Entity
@Table(name = "artista", catalog = "musica")
public class Artista implements java.io.Serializable {

	private String dni;
	private String nombre;
	private Set<Pertenece> perteneces = new HashSet<Pertenece>(0);

	public Artista() {
	}

	public Artista(String dni, String nombre) {
		this.dni = dni;
		this.nombre = nombre;
	}

	public Artista(String dni, String nombre, Set<Pertenece> perteneces) {
		this.dni = dni;
		this.nombre = nombre;
		this.perteneces = perteneces;
	}

	@Id

	@Column(name = "dni", unique = true, nullable = false, length = 10)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "artista")
	public Set<Pertenece> getPerteneces() {
		return this.perteneces;
	}

	public void setPerteneces(Set<Pertenece> perteneces) {
		this.perteneces = perteneces;
	}

}
