package Pojos;
// Generated 26 ene. 2021 7:44:13 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Club generated by hbm2java
 */
@Entity
@Table(name = "club", catalog = "musica")
public class Club implements java.io.Serializable {

	private Integer cod;
	private Grupo grupo;
	private String nombre;
	private String sede;
	private Short num;

	public Club() {
	}

	public Club(Grupo grupo, String nombre) {
		this.grupo = grupo;
		this.nombre = nombre;
	}

	public Club(Grupo grupo, String nombre, String sede, Short num) {
		this.grupo = grupo;
		this.nombre = nombre;
		this.sede = sede;
		this.num = num;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cod", unique = true, nullable = false)
	public Integer getCod() {
		return this.cod;
	}

	public void setCod(Integer cod) {
		this.cod = cod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_gru", nullable = false)
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "sede", length = 30)
	public String getSede() {
		return this.sede;
	}

	public void setSede(String sede) {
		this.sede = sede;
	}

	@Column(name = "num")
	public Short getNum() {
		return this.num;
	}

	public void setNum(Short num) {
		this.num = num;
	}

}
