package Pojos;
// Generated 26 ene. 2021 7:44:13 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Disco generated by hbm2java
 */
@Entity
@Table(name = "disco", catalog = "musica")
public class Disco implements java.io.Serializable {

	private Integer cod;
	private Companyia companyia;
	private Grupo grupo;
	private String nombre;
	private Date fecha;
	private Set<Cancion> cancions = new HashSet<Cancion>(0);

	public Disco() {
	}

	public Disco(Companyia companyia, Grupo grupo) {
		this.companyia = companyia;
		this.grupo = grupo;
	}

	public Disco(Companyia companyia, Grupo grupo, String nombre, Date fecha, Set<Cancion> cancions) {
		this.companyia = companyia;
		this.grupo = grupo;
		this.nombre = nombre;
		this.fecha = fecha;
		this.cancions = cancions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cod", unique = true, nullable = false)
	public Integer getCod() {
		return this.cod;
	}

	public void setCod(Integer cod) {
		this.cod = cod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_comp", nullable = false)
	public Companyia getCompanyia() {
		return this.companyia;
	}

	public void setCompanyia(Companyia companyia) {
		this.companyia = companyia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_gru", nullable = false)
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "esta", catalog = "musica", joinColumns = {
			@JoinColumn(name = "cod", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "can", nullable = false, updatable = false) })
	public Set<Cancion> getCancions() {
		return this.cancions;
	}

	public void setCancions(Set<Cancion> cancions) {
		this.cancions = cancions;
	}

}
